'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB_EaglesInternalE01
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB_EaglesInternalE01")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Branches() As DbSet(Of Branch)
    Public Overridable Property Departments() As DbSet(Of Department)
    Public Overridable Property Documents() As DbSet(Of Document)
    Public Overridable Property M_Document() As DbSet(Of M_Document)
    Public Overridable Property Positions() As DbSet(Of Position)
    Public Overridable Property Referal_Doc() As DbSet(Of Referal_Doc)
    Public Overridable Property RunNoes() As DbSet(Of RunNo)
    Public Overridable Property Sides() As DbSet(Of Side)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property tblAbsents() As DbSet(Of tblAbsent)
    Public Overridable Property tblBookingMessengers() As DbSet(Of tblBookingMessenger)
    Public Overridable Property tblCaseJobs() As DbSet(Of tblCaseJob)
    Public Overridable Property tblFileITs() As DbSet(Of tblFileIT)
    Public Overridable Property tblItJobDocs() As DbSet(Of tblItJobDoc)
    Public Overridable Property tblMenus() As DbSet(Of tblMenu)
    Public Overridable Property tblMessengers() As DbSet(Of tblMessenger)
    Public Overridable Property tblRunningNumbers() As DbSet(Of tblRunningNumber)
    Public Overridable Property tblUsers() As DbSet(Of tblUser)
    Public Overridable Property tblUserGroups() As DbSet(Of tblUserGroup)
    Public Overridable Property tblUserMenus() As DbSet(Of tblUserMenu)
    Public Overridable Property tblUsernames() As DbSet(Of tblUsername)
    Public Overridable Property tblAccessLists() As DbSet(Of tblAccessList)
    Public Overridable Property tblAccessListDetails() As DbSet(Of tblAccessListDetail)
    Public Overridable Property tblDivisions() As DbSet(Of tblDivision)
    Public Overridable Property tblIDRecordings() As DbSet(Of tblIDRecording)

End Class
