'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB_EaglesInternalEntitiesNew
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB_EaglesInternalEntitiesNew")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblBookingMessengers() As DbSet(Of tblBookingMessenger)
    Public Overridable Property tblMessengers() As DbSet(Of tblMessenger)
    Public Overridable Property tblUsers() As DbSet(Of tblUser)
    Public Overridable Property tblUserMenus() As DbSet(Of tblUserMenu)

End Class
